repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    - id: isort
  - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: v0.3.3
    hooks:
    - id: pep257
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.5
    hooks:
    - id: forbid-tabs
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    - id: python-safety-dependencies-check
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: ./backend/venv/bin/pylint
      language: system
      files: \.py$
      args: []
